# Generated by Django 5.2.17 on 2026-08-08 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0016_task_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('skyportal_upload', 'Can upload the task results to SkyPortal'), ('ajst_upload', 'Can upload the task results to AJST catalog'), ('view_all_tasks', 'Can view tasks from all users'), ('edit_all_tasks', 'Can modify tasks from all users')]},
        ),
    ]
