# Generated by Django 5.2.17 on 2026-09-01 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdweb', '0017_alter_task_options'),
        ('stdweb', '0017_task_celery_steps'),
    ]

    operations = [
    ]
